### ISSUE TITLE
[RFC] Call For Maintainers and Project Ownership

### ISSUE THREAD

**Issue by CalMlynarczyk** [serverless/serverless-local-schedule#19]
# Background
United Income was purchased by Capital One in July 2019. As part of our acquisition and integration journey, our team has had to wind down the number of developers maintaining this project.

We still use the Serverless Framework and this plugin on a regular basis, but are currently investigating a move to a Capital One internally-built serverless development framework. Given the uncertain future around our usage of the Serverless Framework and our lessened involvement in its community, we have decided that our team at United Income is no longer able to act as the faithful stewards that this project and its user-base deserve.

# Request for Project Owners
As of June 28th, 2021, United Income will no longer actively contribute to this project. We are asking for the community's assistance in maintaining this project going forward. We are seeking other parties interested in taking ownership of this project who can keep it active going forward. If you are interested in becoming the owner of this project, whether you are a commercial entity or an individual contributor, please contact me at calvin.mlynarczyk@capitalone.com, or Benjamin Samuel at benjamin.samuel@capitalone.com.

# What now?
We have appreciated all of the support, enthusiasm, and contributions from the Serverless Framework community over the years. We really enjoyed being a part of the growing ecosystem around FaaS and serverless computing platforms, especially as we ourselves were also growing from a small financial technology startup to part of one of the largest financial institutions in the United States. However, it is time for us to step aside and let others take the reigns of this project while we move on to the next phase of our company's growth.

We do not want anyone to think our confidence in the Serverless Framework has declined or that this project is dead. Quite the opposite; we still believe that the Serverless Framework is the best tool out there for developing and deploying serverless applications. We at United Income are very excited to see what the future holds for this project and serverless as a whole.

**Comment by medikoo** [comment]
Serverless Framework will be happy to help with maintenance of this project (I'll send and email shortly)

**Comment by pal** [comment]
Hi, what's the status of this? Did you guys take over @medikoo?

**Comment by medikoo** [comment]
@pal still waiting for an answer from UnitedIncome

**Comment by CalMlynarczyk** [comment]
This project has been transferred to the Serverless Framework GitHub organization as the new maintainers.
