### ISSUE TITLE
Is this project dead

### ISSUE THREAD

**Issue by KillDozerX2** [serverless/serverless-local-schedule#24]
If not my organization can take over maintaining it

**Comment by pgrzesik** [comment]
Hey @KillDozerX2 - we're not doing active development but we're happy to accept improvement PRs and will make our best to move them forward to getting merged. Is there anything specific you'd like to address?

**Comment by KillDozerX2** [comment]
There are 3 PR's here that might need a push. #21 is what really affects us.

**Comment by pgrzesik** [comment]
I've added a comment to the linked issue - if you'd like to finalize this PR feel free to pick it up 👍

**Comment by KillDozerX2** [comment]
Got it, thanks.
