### ISSUE TITLE
Released npm version fails validation, was published 4 years ago

### ISSUE THREAD

**Issue by okko** [serverless/serverless-local-schedule#29]
The previous version was published 4 years ago. The instructions at https://www.serverless.com/plugins/serverless-local-schedule still instruct to install that version, 0.1.6.

>Warning: Invalid configuration encountered
>  at 'functions.hello.events.0.schedule': unrecognized property 'timezone'
>
>Learn more about configuration validation here: http://slss.io/configuration-validation

**Comment by okko** [comment]
Workaround is to add it to the devDependencies as follows:

```
    "serverless-local-schedule": "https://github.com/serverless/serverless-local-schedule.git",
```

**Comment by DaveaMorgan** [comment]
Bump on this issue.

**Comment by pgrzesik** [comment]
@Cptmorgan27 v0.1.7 was just released, please let me know if you experience any issues
