### ISSUE TITLE
A rate string array produces hundreds of rules with 1-character ScheduleExpressions

### ISSUE THREAD

**Issue by okko** [serverless/serverless-local-schedule#30]
I'm using TypeScript to configure Serverless. The project was created with `serverless create --template aws-nodejs-typescript`

The Serverless typings (https://github.com/serverless/typescript) require the schedule rate to be an array of strings.

With
```
  events: [
    {
      'schedule': {
        rate: ['cron(45 21 * * ? *)'],
        timezone: 'Europe/Helsinki',
      }
    }
  ],
```
the deployment says
```
Converting local crontabs to UTC crontabs...
Converted 45 21 * * ? * Europe/Helsinki to
               45 19 * 1-2,11-12 ? *
               45 19 1-26 3 ? *
               45 18 27-31 3 ? *
               45 18 * 4-9 ? *
               45 18 1-29 10 ? *
               45 19 30-31 10 ? *
 ```

but it then produces hundreds of AWS::Events::Rules, one for each character of each of the converted rules.

rule 1 has:
```
        "ScheduleExpression": "c",
```
rule 2 has
```
        "ScheduleExpression": "r",
```
rule 3 has
```
        "ScheduleExpression": "o",
```
etc.

These then fail in CloudFormation with `Parameter ScheduleExpression is not valid`.

**Comment by pgrzesik** [comment]
Hello @okko, thanks for reporting. Which version of the plugin are you using?

**Comment by okko** [comment]
@pgrzesik I'm using the version from master, at commit "fix: Support `schedule.rate` defined as an array".

**Comment by pgrzesik** [comment]
Thanks for the details @okko - I've managed to reproduce and pushed a fix - let me know if that solves the problem for you

**Comment by okko** [comment]
@pgrzesik Thank you very much, it did solve the problem. 🙏🏻
