### ISSUE TITLE
Cron for "every minute" expression seems not working

### ISSUE THREAD

**Issue by RichardSilveira** [serverless/serverless-local-schedule#5]
Hi, 
I have this expression in my serverless.yml file: `cron(0/10 8-22 * * ? *)` and after deployed, on CloudWatch the cron looks like: 
![2018-08-07_16-11-09](https://user-images.githubusercontent.com/1668930/43799860-a77a8bd0-9a5c-11e8-924b-164a4cee0e08.jpg)

**Comment by bsamuel-ui** [comment]
Try `*/10` instead of `0/10`.
